# -*- coding: utf-8 -*-
"""CSI5832_train_st1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdStgFrLdc5tmIWe5hSZIwrikm0vrEPa

# SemEval Task 9 POLAR

### Subtask 3 - Manifestation Identification

**Hyper-parameter tune - "xlm-roberta-large"**

By: Kevin Mcmahon, Caleb Kumar

Mount Google Drive to allow access to files stored in the user's Drive. This command will prompt the user for authorization.

Trained xlmr model using opt params from subtask 1.1. Used more data... 10,000 samples per langauge.
Not enough time to to hp tune again using all of the data.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Import statements"""

!pip install optuna
!pip install -U transformers

import pandas as pd

from sklearn.metrics import recall_score, precision_score, f1_score
import numpy as np
import random
import math

import torch

from sklearn.metrics import f1_score

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    set_seed,
)
from torch.utils.data import Dataset
import wandb
from transformers import AutoConfig, AutoModelForSequenceClassification

import optuna
from optuna.samplers import TPESampler

import gc

"""### Importing / Formatting Data"""

base_dir = '/content/drive/MyDrive/SemEval2026/'
data_dir = base_dir + 'data/subtask1_jumbo/'

from sklearn.model_selection import train_test_split

languages = ["eng","arb","deu","spa","zho"]

train_dfs = {}
dev_dfs = {}

for lang in languages:
    train_dfs[lang] = pd.read_csv(data_dir + f"{lang}_10000.csv")
    train_dfs[lang]["language"] = lang

train_full = pd.concat([train_dfs[lang] for lang in languages], ignore_index=True)

# 90/10 split for train/validation, preserving language distribution
train, validation = train_test_split(
    train_full,
    test_size=0.1,
    random_state=42,
    stratify=train_full["language"]
)

"""### Defining Dataset Object"""

# Dataset class (already multi-label friendly)
class PolarizationDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
            return_tensors='pt'
        )

        item = {key: encoding[key].squeeze() for key in encoding.keys()}
        # multi-label → float labels
        item['labels'] = torch.tensor(label, dtype=torch.float)
        return item

"""### Defining Evaluation Metric"""

from sklearn.metrics import f1_score, accuracy_score

def compute_metrics_multilabel(p):
    # p.predictions is a numpy array of logits: (num_examples, num_labels)
    logits = torch.tensor(p.predictions)
    probs = torch.sigmoid(logits).numpy()

    # Try a slightly lower threshold to avoid "all zeros" early on.
    # You can tune this later; 0.3–0.4 is often more sensible for imbalanced multilabel.
    threshold = 0.3
    preds = (probs >= threshold).astype(int)

    labels = p.label_ids

    f1_macro = f1_score(labels, preds, average="macro", zero_division=0)
    # This is *subset* accuracy (exact match over all 6 labels for each example)
    accuracy = accuracy_score(labels, preds)

    return {
        "f1_macro": f1_macro,
        "accuracy": accuracy,
    }

MODEL_NAME = "xlm-roberta-large"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

MAX_LEN = 128

label_cols = [
  "polarization"
]

train_dataset = PolarizationDataset(
    train["text"].tolist(),
    train[label_cols].values.tolist(),
    tokenizer,
    max_length=MAX_LEN,
)

val_dataset = PolarizationDataset(
    validation["text"].tolist(),
    validation[label_cols].values.tolist(),
    tokenizer,
    max_length=MAX_LEN,
)

"""### Defining Callback Metrics

This will allow us to evalaute the performance of the experiment so that we can make sure that the model is learning.
"""

from transformers import TrainerCallback

class EpochMetricsCallback(TrainerCallback):
    def __init__(self, trainer, train_dataset, val_dataset, trial=None):
        super().__init__()
        self.trainer = trainer
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.trial = trial
        self.best_val_f1 = 0.0

    def on_epoch_end(self, args, state, control, **kwargs):
        epoch = state.epoch
        epoch_str = f"{epoch:.0f}" if epoch is not None and not math.isnan(epoch) else "?"

        print(f"\n===== Epoch {epoch_str} =====")

        # ---- Train metrics ----
        train_metrics = self.trainer.evaluate(eval_dataset=self.train_dataset)
        train_loss = train_metrics.get("eval_loss", float("nan"))
        train_f1 = train_metrics.get("eval_f1_macro", float("nan"))
        train_acc = train_metrics.get("eval_accuracy", float("nan"))
        print(
            "Train - "
            f"loss={train_loss:.4f}, "
            f"F1={train_f1:.4f}, "
            f"Acc={train_acc:.4f}"
        )

        # ---- Validation metrics ----
        val_metrics = self.trainer.evaluate(eval_dataset=self.val_dataset)
        val_loss = val_metrics.get("eval_loss", float("nan"))
        val_f1 = val_metrics.get("eval_f1_macro", 0.0)
        val_acc = val_metrics.get("eval_accuracy", float("nan"))
        print(
            "Val   - "
            f"loss={val_loss:.4f}, "
            f"F1={val_f1:.4f}, "
            f"Acc={val_acc:.4f}"
        )
        print("=========================\n")

        # Track best validation F1 for this trial
        if val_f1 > self.best_val_f1:
            self.best_val_f1 = val_f1

        # Report to Optuna + pruning
        if self.trial is not None:
            step = int(epoch) if epoch is not None and not math.isnan(epoch) else state.global_step
            self.trial.report(val_f1, step=step)
            if self.trial.should_prune():
                print(f"Pruning trial at epoch {epoch_str} with val F1={val_f1:.4f}")
                raise optuna.exceptions.TrialPruned()

"""### Results of the study"""

best_params = study.best_trial.params
best_params

"""### Final training run w/ best hyper-parameters / saving model

Training using full training dataset w/ 10k entries / language
"""

import os
from transformers import TrainingArguments, Trainer
from transformers import DataCollatorWithPadding

# Use the same seed helper
seed_everything(GLOBAL_SEED)


#   - train_full_dataset (100%)
train_full_dataset = PolarizationDataset(
    train_full["text"].tolist(),
    train_full[label_cols].values.tolist(),
    tokenizer,
    max_length=MAX_LEN,
)
final_train_dataset = train_full_dataset   # <- or train_dataset if you want

# Optional: still use validation for monitoring
final_val_dataset = val_dataset  # or None if you don't care for dev metrics now

# Unpack best params
lr = best_params["learning_rate"]
num_epochs = best_params["num_train_epochs"]
batch_size = best_params["per_device_train_batch_size"]
weight_decay = best_params["weight_decay"]
warmup_ratio = best_params["warmup_ratio"]
dropout = best_params["dropout"]

# Build model with best dropout
final_model = build_model(dropout=dropout)

# Where to save the final model
output_dir = "/content/drive/MyDrive/SemEval2026/models/xlmr_best_st12"

training_args = TrainingArguments(
    output_dir=output_dir,
    learning_rate=lr,
    num_train_epochs=num_epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=weight_decay,
    warmup_ratio=warmup_ratio,

    evaluation_strategy="epoch" if final_val_dataset is not None else "no",
    save_strategy="epoch" if final_val_dataset is not None else "no",
    load_best_model_at_end=(final_val_dataset is not None),
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_steps=100,
    save_total_limit=1,
    remove_unused_columns=False,
    fp16=torch.cuda.is_available(),
)

data_collator = DataCollatorWithPadding(tokenizer)

final_trainer = Trainer(
    model=final_model,
    args=training_args,
    train_dataset=final_train_dataset,
    eval_dataset=final_val_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics_multilabel,
)

final_trainer.train()

# Save the final model + tokenizer
final_trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

print("Final model saved to:", output_dir)