# -*- coding: utf-8 -*-
"""CSCI5832_Ensemble_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yR43EZcdn25FuSqrNXN3C1U2wa9WB0fE

# Ensemble Model for Subtask 3

In this notebook we will be wiring together the best performing models from hyper-parameter tuning together to hopefully improve F1 Score.

### Final Predictions for Submission will be created in this notebook

### Mount Drive + Set Base Directory Paths
"""

from google.colab import drive
drive.mount('/content/drive')

base_dir = '/content/drive/MyDrive/SemEval2026/'
data_dir = base_dir + 'data/subtask3/'

model_dirs = {
    "xlmr": base_dir + "models/subtask3_xlmr_large",
    "twitter": base_dir + "models/subtask3_twitter_xlm_base",
    "mdeberta": base_dir + "models/subtask3_mdeberta_v3_base",
}

"""### Imports + label setup"""

import os
import numpy as np
import pandas as pd

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)

from sklearn.metrics import f1_score, accuracy_score

label_cols = [
    "vilification",
    "extreme_language",
    "stereotype",
    "invalidation",
    "lack_of_empathy",
    "dehumanization",
]

NUM_LABELS = len(label_cols)

"""### Loading all data properly"""

from sklearn.model_selection import train_test_split

languages = ["eng","spa","arb","deu","zho"]  # or update to your final 3 / 5 languages

train_dfs = {}
dev_dfs = {}

for lang in languages:
    train_dfs[lang] = pd.read_csv(data_dir + f"train/{lang}.csv")
    train_dfs[lang]["language"] = lang
    dev_dfs[lang] = pd.read_csv(data_dir + f"dev/{lang}.csv")
    dev_dfs[lang]["language"] = lang

train_full = pd.concat([train_dfs[lang] for lang in languages], ignore_index=True)
dev_full = pd.concat([dev_dfs[lang] for lang in languages], ignore_index=True)

train, validation = train_test_split(
    train_full,
    test_size=0.2,
    random_state=42,
    stratify=train_full["language"]
)

"""### Defining Dataset Class (the same as before)"""

class PolarizationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]

        encoded = self.tokenizer(
            text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
        )

        item = {k: torch.tensor(v) for k, v in encoded.items()}
        item["labels"] = torch.tensor(label, dtype=torch.float)
        return item

"""Verifying shape of labels"""

y_true = validation[label_cols].values.astype(int)
print("y_true shape:", y_true.shape)

"""### Helper function to get logits from saved models

This function:

*   Loads a model + tokenizer from a directory
*   Buils dev/test datasets
* Runs `Trainer.predict` to get logits


"""

def get_logits_for_model(model_dir, texts, labels=None, max_len=128, batch_size=32):
    """
    model_dir: folder with config + pytorch_model.bin + tokenizer
    texts: list of text strings
    labels: np.array or list of label vectors (for Dataset); if None, dummy 0s are used
    """
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)

    if labels is None:
        labels = np.zeros((len(texts), NUM_LABELS), dtype=int)

    dataset = PolarizationDataset(
        texts=texts,
        labels=labels,
        tokenizer=tokenizer,
        max_length=max_len,
    )

    args = TrainingArguments(
        output_dir="/content/tmp_eval",
        per_device_eval_batch_size=batch_size,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=args,
        eval_dataset=dataset,
        data_collator=DataCollatorWithPadding(tokenizer),
    )

    preds = trainer.predict(dataset)
    logits = preds.predictions  # shape (N, NUM_LABELS)

    return logits

"""### Compute dev logits for each model"""

valid_logits = {}

texts_valid = validation["text"].tolist()

for name, mdir in model_dirs.items():
    print(f"Getting validation logits for {name} from {mdir}")
    logits = get_logits_for_model(
        model_dir=mdir,
        texts=texts_valid,
        labels=y_true,     # we do have labels for dev
        max_len=128,
        batch_size=32,
    )
    valid_logits[name] = logits

# sanity checks
for name, logits in valid_logits.items():
    print(name, logits.shape)

"""### Evaluating single models on dev (for comparison)

This gives the **per-model dev scores** using a global 0.3 threshold. Can tweak if needed, but should be fine for comparison.
"""

def logits_to_metrics(logits, y_true, thresh=0.3):
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    preds = (probs >= thresh).astype(int)

    macro_f1 = f1_score(y_true, preds, average="macro", zero_division=0)
    acc = accuracy_score(y_true, preds)
    return macro_f1, acc

for name, logits in valid_logits.items():
    f1, acc = logits_to_metrics(logits, y_true, thresh=0.3)
    print(f"{name}: F1={f1:.4f}, Acc={acc:.4f}")

"""###Build ensemble + tune per-label thresholds on dev

Ensemble = average logits from the 3 models, then tune thresholds per label to maxmize macro-F! on dev.

This provides us with;
*   Dev macro-F1 for each individual model
*   Dev macro-F1 for the ensemble
*   Threshold per label to reuse on test




"""

# Simple equal-weight ensemble on logits
logits_x = valid_logits["xlmr"]
logits_t = valid_logits["twitter"]
logits_m = valid_logits["mdeberta"]

logits_ens = (logits_x + logits_t + logits_m) / 3.0
probs_ens = 1.0 / (1.0 + np.exp(-logits_ens))  # sigmoid

num_labels = NUM_LABELS
best_thresh = [0.5] * num_labels

for j in range(num_labels):
    best_f1_j = 0.0
    best_t_j = 0.5
    for t in np.linspace(0.1, 0.9, 81):  # 0.01 steps
        preds_j = (probs_ens[:, j] >= t).astype(int)
        f1_j = f1_score(y_true[:, j], preds_j, zero_division=0)
        if f1_j > best_f1_j:
            best_f1_j = f1_j
            best_t_j = t
    best_thresh[j] = best_t_j
    print(f"Label {label_cols[j]}: best_thresh={best_t_j:.2f}, best_f1={best_f1_j:.3f}")

# Evaluate ensemble macro-F1 with these thresholds
preds_all = np.zeros_like(y_true)
for j in range(num_labels):
    preds_all[:, j] = (probs_ens[:, j] >= best_thresh[j]).astype(int)

macro_f1 = f1_score(y_true, preds_all, average="macro", zero_division=0)
acc = accuracy_score(y_true, preds_all)
print("\nEnsemble on dev:")
print(f"Macro-F1={macro_f1:.4f}, Acc={acc:.4f}")
print("Best thresholds per label:", dict(zip(label_cols, best_thresh)))

"""### Get dev logits and apply ensemble

Same as validation, but no labels.
"""

texts_test = dev_full["text"].tolist()

test_logits = {}
for name, mdir in model_dirs.items():
    print(f"Getting test logits for {name}")
    logits = get_logits_for_model(
        model_dir=mdir,
        texts=texts_test,
        labels=None,  # no test labels
        max_len=128,
        batch_size=32,
    )
    test_logits[name] = logits

# Ensemble test logits
logits_x_test = test_logits["xlmr"]
logits_t_test = test_logits["twitter"]
logits_m_test = test_logits["mdeberta"]

logits_ens_test = (logits_x_test + logits_t_test + logits_m_test) / 3.0
probs_ens_test = 1.0 / (1.0 + np.exp(-logits_ens_test))

"""Apple the tuned thresholds learend above."""

preds_test = np.zeros_like(probs_ens_test, dtype=int)
for j in range(num_labels):
    preds_test[:, j] = (probs_ens_test[:, j] >= best_thresh[j]).astype(int)

print("preds_test shape:", preds_test.shape)

"""###Build submission dataframe and save"""

submission = pd.DataFrame({
    "id": dev_full["id"].values,
})

for j, col in enumerate(label_cols):
    submission[col] = preds_test[:, j]

# UPDATING COLUMN NAMES TO ACTUAL NAMES
# HAD COLUMNS MIS-LABELED THROUGHOUT ENTIRE TRAINING PROCESS
# Stuck to the bad naming convention throughout and
# finally switching back for submission
submission = submission.rename(
    columns={
        "vilification": "stereotype",
        "extreme_language": "vilification",
        "stereotype": "dehumanization",
        "invalidation": "lack_of_empathy",
        "lack_of_empathy": "extreme_language",
        "dehumanization": "invalidation",
    }
)

submission.head()

"""Saving the .df partitioned by language into CSVs"""

import os

# Make sure this exists
out_root = os.path.join(base_dir, "submissions")
os.makedirs(out_root, exist_ok=True)

# Map from the first 2 characters of id → desired lang code
prefix_to_lang = {
    "en": "eng",
    "sp": "spa",
    "de": "deu",
    "ar": "arb",
    "zh": "zho",
}

# Add a prefix column based on the first 2 letters of id
submission["prefix"] = submission["id"].astype(str).str[:2]

for prefix, lang_code in prefix_to_lang.items():
    df_lang = submission[submission["prefix"] == prefix].copy()
    # Drop the helper column before saving
    df_lang = df_lang.drop(columns=["prefix"])

    out_path = os.path.join(out_root, f"pred_{lang_code}.csv")
    df_lang.to_csv(out_path, index=False)
    print(f"Saved {len(df_lang)} rows to {out_path}")