# -*- coding: utf-8 -*-
"""train_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYON0VCwngQ8eUk-LC6XEqFvgyw3SgF3

# SemEval Task 9 POLAR

### Subtask 3 - Manifestation Identification

## Training Model(s) w/ optimal hp's found

With the optimal parameters found in hyper-parameter tuning, this notebook trains and saves the best performing models with those hyper-parameters. This notebook is ran once and then once all models are created / saved they can be fromed into and ensemble. All models from hp-tuning are trained /saved in this notebook except for the large google/rembert model which under-performed with a maximum Macro-F1 of just 0.28.

**By: Kevin McMahon, Caleb Kumar**

Mount Google Drive to allow access to files stored in the user's Drive. This command will prompt the user for authorization.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Import statements"""

!pip install optuna
!pip install -U transformers

import pandas as pd

from sklearn.metrics import recall_score, precision_score, f1_score
import numpy as np
import random
import math

import torch

from sklearn.metrics import f1_score

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    set_seed,
)
from torch.utils.data import Dataset
import wandb
from transformers import AutoConfig, AutoModelForSequenceClassification

import optuna
from optuna.samplers import TPESampler

import gc

"""**Saving the Data Directory**


"""

base_dir = '/content/drive/MyDrive/SemEval2026/'
data_dir = base_dir + 'data/subtask3/'

"""### Importing / Formatting Data"""

from sklearn.model_selection import train_test_split

languages = ["eng","spa","arb","deu","zho"]  # or update to your final 3 / 5 languages

train_dfs = {}
dev_dfs = {}

for lang in languages:
    train_dfs[lang] = pd.read_csv(data_dir + f"train/{lang}.csv")
    train_dfs[lang]["language"] = lang
    dev_dfs[lang] = pd.read_csv(data_dir + f"dev/{lang}.csv")
    dev_dfs[lang]["language"] = lang

train_full = pd.concat([train_dfs[lang] for lang in languages], ignore_index=True)
dev_full = pd.concat([dev_dfs[lang] for lang in languages], ignore_index=True)

train, validation = train_test_split(
    train_full,
    test_size=0.2,
    random_state=42,
    stratify=train_full["language"]
)

"""###Seed helper to ensure reproducibility"""

GLOBAL_SEED = 42

def seed_everything(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    set_seed(seed)  # HF helper

"""### Defining Dataset Object"""

# Dataset class (already multi-label friendly)
class PolarizationDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
            return_tensors='pt'
        )

        item = {key: encoding[key].squeeze() for key in encoding.keys()}
        # multi-label → float labels
        item['labels'] = torch.tensor(label, dtype=torch.float)
        return item

"""### Defining Evaluation Metric"""

from sklearn.metrics import f1_score, accuracy_score

def compute_metrics_multilabel(p):
    # p.predictions is a numpy array of logits: (num_examples, num_labels)
    logits = torch.tensor(p.predictions)
    probs = torch.sigmoid(logits).numpy()

    # Try a slightly lower threshold to avoid "all zeros" early on.
    # You can tune this later; 0.3–0.4 is often more sensible for imbalanced multilabel.
    threshold = 0.3
    preds = (probs >= threshold).astype(int)

    labels = p.label_ids

    f1_macro = f1_score(labels, preds, average="macro", zero_division=0)
    # This is *subset* accuracy (exact match over all 6 labels for each example)
    accuracy = accuracy_score(labels, preds)

    return {
        "f1_macro": f1_macro,
        "accuracy": accuracy,
    }

"""### Per-Epoch Callbacks for Evaluating Performance"""

from transformers import TrainerCallback

class EpochMetricsCallback(TrainerCallback):
    def __init__(self, trainer, train_dataset, val_dataset, trial=None):
        super().__init__()
        self.trainer = trainer
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.trial = trial
        self.best_val_f1 = 0.0

    def on_epoch_end(self, args, state, control, **kwargs):
        epoch = state.epoch
        epoch_str = f"{epoch:.0f}" if epoch is not None and not math.isnan(epoch) else "?"

        print(f"\n===== Epoch {epoch_str} =====")

        # ---- Train metrics ----
        train_metrics = self.trainer.evaluate(eval_dataset=self.train_dataset)
        train_loss = train_metrics.get("eval_loss", float("nan"))
        train_f1 = train_metrics.get("eval_f1_macro", float("nan"))
        train_acc = train_metrics.get("eval_accuracy", float("nan"))
        print(
            "Train - "
            f"loss={train_loss:.4f}, "
            f"F1={train_f1:.4f}, "
            f"Acc={train_acc:.4f}"
        )

        # ---- Validation metrics ----
        val_metrics = self.trainer.evaluate(eval_dataset=self.val_dataset)
        val_loss = val_metrics.get("eval_loss", float("nan"))
        val_f1 = val_metrics.get("eval_f1_macro", 0.0)
        val_acc = val_metrics.get("eval_accuracy", float("nan"))
        print(
            "Val   - "
            f"loss={val_loss:.4f}, "
            f"F1={val_f1:.4f}, "
            f"Acc={val_acc:.4f}"
        )
        print("=========================\n")

        # Track best validation F1 for this trial
        if val_f1 > self.best_val_f1:
            self.best_val_f1 = val_f1

        # Report to Optuna + pruning
        if self.trial is not None:
            step = int(epoch) if epoch is not None and not math.isnan(epoch) else state.global_step
            self.trial.report(val_f1, step=step)
            if self.trial.should_prune():
                print(f"Pruning trial at epoch {epoch_str} with val F1={val_f1:.4f}")
                raise optuna.exceptions.TrialPruned()

"""### Build Model Helper Fcn

This new function takes in model name to be used to train multiple models
"""

from transformers import AutoConfig, AutoModelForSequenceClassification

def build_model(model_name: str, dropout: float):
    config = AutoConfig.from_pretrained(
        model_name,
        num_labels=len(label_cols),
        problem_type="multi_label_classification",
        hidden_dropout_prob=dropout,
        attention_probs_dropout_prob=dropout,
    )
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        config=config,
    )
    return model

"""### Train the model(s)

This the function that trains each of the models
"""

import os
import gc
import torch
from transformers import TrainingArguments, Trainer, AutoTokenizer
from transformers import DataCollatorWithPadding

def train_and_save_model(
    model_name: str,
    best_params: dict,
    save_subdir: str,
    max_len: int = 128,
):
    """
    Train and save a single model (XLM-R, Twitter-XLM-R, DeBERTa) with fixed best_params.
    """

    print(f"\n===== Training {model_name} =====")

    # Reproducibility
    seed_everything(GLOBAL_SEED)

    # 1) Load tokenizer for this model
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # 2) Build datasets for this model (tokenization is model-specific!)
    train_dataset = PolarizationDataset(
        train["text"].tolist(),
        train[label_cols].values.tolist(),
        tokenizer,
        max_length=max_len,
    )

    val_dataset = PolarizationDataset(
        validation["text"].tolist(),
        validation[label_cols].values.tolist(),
        tokenizer,
        max_length=max_len,
    )

    # 3) Build model
    model = build_model(model_name, dropout=best_params["dropout"])

    # 4) Define save directory for this model
    save_dir = os.path.join(base_dir, "models", save_subdir)
    os.makedirs(save_dir, exist_ok=True)

    # 5) Training args
    training_args = TrainingArguments(
        output_dir=save_dir,
        num_train_epochs=best_params["num_train_epochs"],
        learning_rate=best_params["learning_rate"],
        per_device_train_batch_size=best_params["per_device_train_batch_size"],
        per_device_eval_batch_size=best_params["per_device_train_batch_size"],
        save_strategy="no",
        logging_steps=600,
        report_to="none",
        weight_decay=best_params["weight_decay"],
        warmup_ratio=best_params["warmup_ratio"],
        metric_for_best_model="f1_macro",
        load_best_model_at_end=False,
        fp16=torch.cuda.is_available(),
        seed=GLOBAL_SEED,
        data_seed=GLOBAL_SEED,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics_multilabel,
        data_collator=DataCollatorWithPadding(tokenizer),
    )

    # Optional: epoch-wise logging
    epoch_cb = EpochMetricsCallback(
        trainer=trainer,
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        trial=None,
    )
    trainer.add_callback(epoch_cb)

    print("Trainer device:", trainer.args.device)

    # 6) Train + eval
    trainer.train()
    final_eval = trainer.evaluate()
    print(f"Final eval metrics for {model_name}:", final_eval)

    # 7) Save final model + tokenizer
    trainer.save_model(save_dir)
    tokenizer.save_pretrained(save_dir)

    # 8) Cleanup
    del trainer, model, tokenizer, train_dataset, val_dataset
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print(f"Saved {model_name} to {save_dir}")

"""### Defining best hyper-params for each model

Allows this single script to train all of the models in a single go
"""

# REPLACE these with your true best params from HPO for each model

best_params_xlmr = {
    "learning_rate": 8.39e-06,
    "num_train_epochs": 8,
    "per_device_train_batch_size": 16,
    "weight_decay": 0.0656,
    "warmup_ratio": 0.0251,
    "dropout": 0.1204,
}

best_params_twitter = {
    'learning_rate': 1.5705134127086373e-05,
    'num_train_epochs': 7,
    'per_device_train_batch_size': 16,
    'weight_decay': 0.04703085746394833,
    'warmup_ratio': 0.07204629975258536,
    'dropout': 0.15385788772690773
}

best_params_mdeberta = {
    'learning_rate': 1.9071114432274296e-05,
    'num_train_epochs': 8,
    'per_device_train_batch_size': 16,
    'weight_decay': 0.07056562475456848,
    'warmup_ratio': 0.035855957038224535,
    'dropout': 0.17914280432053034
}

"""**Organizing Model names and hyper-parameters for efficient training**

model_name, params, subdir
"""

models_to_train = [
    (
        "xlm-roberta-large",
        best_params_xlmr,
        "subtask3_xlmr_large",              # folder name under base_dir/models/
    ),
    (
        "cardiffnlp/twitter-xlm-roberta-base",
        best_params_twitter,
        "subtask3_twitter_xlm_base",
    ),
    (
        "microsoft/mdeberta-v3-base",
        best_params_mdeberta,
        "subtask3_mdeberta_v3_base",
    ),
]

"""### Training / saving all models"""

for model_name, params, subdir in models_to_train:
    train_and_save_model(
        model_name=model_name,
        best_params=params,
        save_subdir=subdir,
        max_len=128,   # or whatever MAX_LEN you settled on
    )